"""Run the REAL ComfyUI image pipelines on the GPU and record what happened.

Why this exists: difftest_refactor.py proves the emitted workflow JSON is
byte-identical before and after the refactor, but identical JSON is not a
rendered image. Nothing had actually executed the contained-edit, transfer,
object-removal, object-insert or face-enhance paths against a live GPU since
image.py was split into eight modules.

Design:

  * every stage runs with a FIXED seed, so a pixel difference between two runs
    of the same commit is not expected and a difference between commits is
    evidence rather than noise;
  * every workflow submitted to ComfyUI is captured by hooking
    comfy_client._submit_and_poll / _submit_and_collect, so when pixels differ
    we can still say whether the GRAPH differed — that separates "the refactor
    changed what we asked for" from "the sampler is nondeterministic";
  * the base images are generated by the first stage from a fixed seed rather
    than shipped as fixtures, so the whole run is self-contained and the inputs
    are identical across commits;
  * results go to JSON keyed by stage, so two commits can be diffed field by
    field instead of by reading two logs side by side.

Run:  PYTHONPATH=. python -u bench/gputest_pipelines.py <tag>
Then: python bench/gputest_pipelines.py --diff <tagA> <tagB>
"""
import hashlib
import json
import os
import sys
import threading
import time
import traceback

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

OUT_ROOT = os.path.join(os.environ.get("GPUTEST_OUT", os.path.join(ROOT, "_gputest")))


def sha(path_or_bytes):
    if isinstance(path_or_bytes, bytes):
        return hashlib.sha256(path_or_bytes).hexdigest()[:16]
    try:
        with open(path_or_bytes, "rb") as fh:
            return hashlib.sha256(fh.read()).hexdigest()[:16]
    except Exception:
        return None


def describe(path):
    """Dimensions + format of a produced file, or why we cannot read it."""
    if not path or not os.path.exists(path):
        return {"exists": False}
    info = {"exists": True, "bytes": os.path.getsize(path), "sha256_16": sha(path)}
    try:
        from PIL import Image
        with Image.open(path) as im:
            info.update(size=list(im.size), format=im.format, mode=im.mode)
    except Exception as exc:
        info["pil_error"] = str(exc)[:120]
    return info


# ---------------------------------------------------------------- workflow tap
SUBMITTED = []           # every graph handed to ComfyUI, in order


def install_tap():
    """Record each workflow submitted, keyed by the node types it contains.

    Hashing the whole graph would flag harmless things (uploaded filenames carry
    a timestamp), so we record BOTH: a full hash and a structural fingerprint of
    node classes and their counts. The fingerprint is what a refactor could
    plausibly break; the hash is a tiebreaker.
    """
    import comfy_client as CC

    def fingerprint(wf):
        try:
            kinds = {}
            for node in wf.values():
                k = node.get("class_type", "?")
                kinds[k] = kinds.get(k, 0) + 1
            return {"nodes": len(wf), "kinds": dict(sorted(kinds.items()))}
        except Exception as exc:
            return {"error": str(exc)[:80]}

    for name in ("_submit_and_poll", "_submit_and_collect"):
        orig = getattr(CC, name, None)
        if orig is None:
            continue

        def make(orig=orig, name=name):
            def wrapper(ctx, workflow, *a, **k):
                SUBMITTED.append({
                    "via": name,
                    "label": k.get("label", "") or (a[1] if len(a) > 1 else ""),
                    "fingerprint": fingerprint(workflow),
                    "graph_sha": sha(json.dumps(workflow, sort_keys=True,
                                                default=str).encode()),
                })
                return orig(ctx, workflow, *a, **k)
            return wrapper
        setattr(CC, name, make())


def make_ctx():
    import models
    return models.Context(models=None, transcription_cache={}, cache_file=None,
                          asr_lock=threading.Lock(), tts_lock=threading.Lock())


RESULTS = {}


def stage(name, fn):
    """Run one pipeline stage; never let a failure stop the rest of the sweep."""
    mark = len(SUBMITTED)
    t0 = time.time()
    rec = {"stage": name}
    try:
        out = fn()
        rec["ok"] = True
        rec["returned"] = out if isinstance(out, (str, type(None))) else str(type(out))
        if isinstance(out, dict):
            rec["returned"] = {k: str(v)[:120] for k, v in list(out.items())[:6]}
            out = out.get("path") or out.get("image_path")
        rec["output"] = describe(out) if isinstance(out, str) else {"exists": False}
    except Exception as exc:
        rec["ok"] = False
        rec["error"] = f"{type(exc).__name__}: {exc}"[:300]
        rec["traceback_tail"] = traceback.format_exc().strip().splitlines()[-1][:200]
    rec["seconds"] = round(time.time() - t0, 1)
    rec["workflows"] = SUBMITTED[mark:]
    RESULTS[name] = rec
    status = "OK " if rec.get("ok") else "ERR"
    got = rec.get("output", {})
    extra = f"{got.get('size')} {got.get('format')}" if got.get("exists") else rec.get("error", "no file")
    print(f"[{status}] {name:34} {rec['seconds']:6.1f}s  {len(rec['workflows'])} wf  {extra}",
          flush=True)
    return rec


def main(tag):
    outdir = os.path.join(OUT_ROOT, tag)
    os.makedirs(outdir, exist_ok=True)
    install_tap()
    import image as I
    ctx = make_ctx()
    SEED = 12345

    print(f"=== GPU pipeline sweep [{tag}] — image.py at "
          f"{sum(1 for _ in open(os.path.join(ROOT, 'imaging/image.py'), encoding='utf-8'))} lines\n", flush=True)

    # 1. txt2img — also produces the base image every later stage edits, so the
    #    inputs are identical across commits without shipping binary fixtures.
    base = {}
    def _gen():
        out = I.generate_image_with_comfy(ctx, "a single red apple on a wooden table",
                                          steps=8, seed=SEED, width=512, height=512)
        base["apple"] = out if isinstance(out, str) else (out or {}).get("path")
        return out
    stage("01_generate_txt2img", _gen)

    def _portrait():
        out = I.generate_image_with_comfy(ctx, "portrait photograph of a person, face visible",
                                          steps=8, seed=SEED + 1, width=512, height=512)
        base["face"] = out if isinstance(out, str) else (out or {}).get("path")
        return out
    stage("02_generate_portrait", _portrait)

    apple = lambda: base.get("apple")
    face = lambda: base.get("face")

    def guard(fn):
        def run():
            if not apple():
                raise RuntimeError("no base image — stage 01 failed, skipped")
            return fn()
        return run

    stage("03_redraw_img2img", guard(
        lambda: I.redraw_image_with_comfy(ctx, apple(), "a green apple", seed=SEED)))

    stage("04_outpaint", guard(
        lambda: I.outpaint_image_with_comfy(ctx, apple(), "wooden table", right=128, seed=SEED)))

    # region given explicitly so this stage does NOT depend on the LLM grounder
    stage("05_insert_object", guard(
        lambda: I.insert_object_with_comfy(ctx, apple(), "a silver fork",
                                           region=(0.05, 0.55, 0.45, 0.95), seed=SEED)))

    stage("06_remove_object", guard(
        lambda: I.remove_object_with_comfy(ctx, apple(), "apple", seed=SEED)))

    stage("07_contained_edit", guard(
        lambda: I.edit_region_contained_with_comfy(ctx, apple(), "apple",
                                                   "a green apple", seed=SEED)))

    stage("08_contained_cropped", guard(
        lambda: I.edit_region_contained_cropped(ctx, apple(), "apple",
                                                "a green apple", seed=SEED)))

    stage("09_inpaint_region", guard(
        lambda: I.inpaint_region_with_comfy(ctx, apple(), "apple", "a green apple", seed=SEED)))

    stage("10_firered_edit", guard(
        lambda: I.edit_image_with_firered(ctx, apple(), "make the apple green", seed=SEED)))

    def _faces():
        if not face():
            raise RuntimeError("no portrait — stage 02 failed, skipped")
        return I.enhance_faces_with_comfy(ctx, face())
    stage("11_enhance_faces", _faces)

    def _hands():
        if not face():
            raise RuntimeError("no portrait — stage 02 failed, skipped")
        return I.fix_hands(ctx, face(), seed=SEED)
    stage("12_fix_hands", _hands)

    def _transfer():
        if not (apple() and face()):
            raise RuntimeError("missing base images, skipped")
        # references are ReferenceImage objects, not bare paths — infer_reference_roles
        # assigns .role in place, so a list of str raises AttributeError.
        refs = [I.ReferenceImage(face())]
        return I.plan_and_execute_transfer(ctx, apple(), refs,
                                           "put the person next to the apple", seed=SEED)
    stage("13_transfer", _transfer)

    report = {
        "tag": tag,
        "image_py_lines": sum(1 for _ in open(os.path.join(ROOT, "imaging/image.py"), encoding="utf-8")),
        "root": ROOT,
        "stages": RESULTS,
    }
    path = os.path.join(outdir, "report.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=1, sort_keys=True)
    ok = sum(1 for r in RESULTS.values() if r.get("ok"))
    print(f"\n{ok}/{len(RESULTS)} stages returned a result — report at {path}", flush=True)
    return 0


def diff(a, b):
    """Compare two runs field by field, separating graph from pixel differences."""
    ra = json.load(open(os.path.join(OUT_ROOT, a, "report.json"), encoding="utf-8"))
    rb = json.load(open(os.path.join(OUT_ROOT, b, "report.json"), encoding="utf-8"))
    print(f"{'stage':34} {'ok':>7} {'graph':>9} {'size':>11} {'pixels':>9}")
    print("-" * 76)
    verdicts = {}
    for name in sorted(set(ra["stages"]) | set(rb["stages"])):
        sa, sb = ra["stages"].get(name, {}), rb["stages"].get(name, {})
        oka, okb = sa.get("ok"), sb.get("ok")
        fa = [w["fingerprint"] for w in sa.get("workflows", [])]
        fb = [w["fingerprint"] for w in sb.get("workflows", [])]
        ga = [w["graph_sha"] for w in sa.get("workflows", [])]
        gb = [w["graph_sha"] for w in sb.get("workflows", [])]
        oa, ob = sa.get("output", {}), sb.get("output", {})
        graph = "same" if fa == fb else "DIFFER"
        if fa == fb and ga != gb:
            graph = "same*"          # structurally identical, bytes differ (timestamps)
        size = "same" if oa.get("size") == ob.get("size") else "DIFFER"
        pix = "same" if oa.get("sha256_16") == ob.get("sha256_16") else "differ"
        if not (oa.get("exists") and ob.get("exists")):
            pix = "n/a"
        okc = "same" if oka == okb else f"{oka}->{okb}"
        verdicts[name] = dict(ok=okc, graph=graph, size=size, pixels=pix)
        print(f"{name:34} {okc:>7} {graph:>9} {size:>11} {pix:>9}")
    print("\nlegend: graph=DIFFER is a REGRESSION (we asked ComfyUI for a different")
    print("        thing). graph=same with pixels=differ is sampler nondeterminism,")
    print("        not a refactor bug. same* = same structure, byte diff (timestamps).")
    return verdicts


def verdict(before, after, control):
    """Judge before-vs-after against a NOISE FLOOR measured at one commit.

    Why this mode exists: a plain two-way diff called five stages 'DIFFER' that
    were not regressions at all. The mask-gated paths (SAM3 grounding + the
    STAGE-0 gate's retry ladder) submit a DIFFERENT NUMBER of jobs depending on
    what the gate sees, and what it sees depends on input pixels that are
    themselves nondeterministic. So "the graph changed" is only evidence of a
    regression for a stage that is otherwise STABLE.

    `control` must be a second run of the SAME commit as `after`. Any stage that
    differs between `after` and `control` is unstable by construction, and a
    difference there cannot be attributed to the refactor. Stages that are
    stable in the control and still differ before-vs-after are the real
    candidates — those are the ones worth a human's time.
    """
    R = {}
    for tag in (before, after, control):
        R[tag] = json.load(open(os.path.join(OUT_ROOT, tag, "report.json"),
                                encoding="utf-8"))["stages"]

    def shape(stage_rec):
        return [w["fingerprint"] for w in stage_rec.get("workflows", [])]

    print(f"noise floor = {after} vs {control} (same commit)\n")
    print(f"{'stage':24} {'before':>7} {'after':>6} {'control':>8}  verdict")
    print("-" * 74)
    regressions, noisy, stable = [], [], []
    for name in sorted(set(R[before]) | set(R[after])):
        b, a, c = R[before].get(name, {}), R[after].get(name, {}), R[control].get(name, {})
        nb, na, nc = len(shape(b)), len(shape(a)), len(shape(c))
        unstable = shape(a) != shape(c)
        changed = shape(b) != shape(a)
        if unstable:
            v = "noise (varies at one commit)"
            noisy.append(name)
        elif changed:
            v = "REGRESSION CANDIDATE"
            regressions.append(name)
        else:
            v = "stable and identical"
            stable.append(name)
        print(f"{name:24} {nb:>7} {na:>6} {nc:>8}  {v}")

    print(f"\n{len(stable)} stable+identical, {len(noisy)} noisy, "
          f"{len(regressions)} regression candidates")
    if regressions:
        print("LOOK AT THESE: " + ", ".join(regressions))
    else:
        print("No stage is both STABLE at one commit and CHANGED across commits.")
    return regressions


if __name__ == "__main__":
    if len(sys.argv) >= 5 and sys.argv[1] == "--verdict":
        sys.exit(1 if verdict(sys.argv[2], sys.argv[3], sys.argv[4]) else 0)
    if len(sys.argv) >= 4 and sys.argv[1] == "--diff":
        diff(sys.argv[2], sys.argv[3])
    else:
        sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "head"))
